#@data/values
---
images:
  capi: gcr.io/peripli/cloud-controller-ng@sha256:15a7b92d1a8039f334c59ab3ad2046811afd2a76c2cd595114ae3decea3d6bb7

{{- if .Values.cc_db }}
capi:
  database:
    adapter: {{ .Values.cc_db_values.adapter }}
    host: {{ .Values.cc_db_values.host }}
    port: {{ .Values.cc_db_values.port }}
    user: {{ .Values.cc_db_values.user }}
    password: {{ .Values.cc_db_values.password }}
    name: {{ .Values.cc_db_values.database }}
{{- end }}
