---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: overlays/_ytt_lib
  contents:
  - path: github.com/cloudfoundry/cf-for-k8s
    git:
      url: https://github.com/cloudfoundry/cf-for-k8s
      ref: v0.3.0
    includePaths:
    - config/**/*
