#@ load("@ytt:base64", "base64")
#@ credentials = self.cf4k8s.credentials()
#@ uaa_credentials = self.cf4k8s.uaa_credentials()
---
apiVersion: v1
kind: Secret
metadata:
    name: kubecf.var-cf-admin-password
    namespace: kubecf
type: Opaque
data:
    username: #@ base64.encode(credentials.username)
    password: #@ base64.encode(credentials.password)
---
apiVersion: v1
kind: Secret
metadata:
    name: kubecf.var-uaa-admin-client-secret
    namespace: kubecf
type: Opaque
data:
    username: #@ base64.encode(uaa_credentials.username)
    password: #@ base64.encode(uaa_credentials.password)
