#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.and_op(overlay.subset({"metadata":{"name":"istio-ingressgateway", "namespace" : "cf-system"}}), overlay.subset({"kind": "Gateway"}))
---
spec:
  servers:
  #@overlay/match by=overlay.subset({"tls": {"credentialName": "istio-ingressgateway-certs"}})
  - hosts:
    {{- range $app_domain := .Values.cf4k8s.app_domains }}
    #@overlay/append
    - "*.{{ $app_domain }}"
    {{- end }}

