#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Secret", "metadata":{"namespace": "cf-workloads", "name":"app-registry-credentials"}})
---
metadata:
  annotations:
    #@overlay/remove
    kapp.k14s.io/versioned: ""
