#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Builder", "metadata":{"namespace": "cf-workloads-staging", "name":"cf-autodetect-builder"}})
---
spec:
  #@overlay/replace
  #@overlay/match missing_ok=True
  image: gcr.io/peripli/paketo-builder@sha256:8941220e51ebcd62b777be07c1a3273ae187d4312b7fa828dd8615c18f07b7c7
