#@data/values
---
#@overlay/match missing_ok=True
gardener:
  sub_domains: #@ self.sub_domains
  istio_ingressgateway_credential_name: "cf-4-k8s-ingressgateway-certs"
  default_identity_provider: #@ self.default_identity_provider
  #@ if/end self.certificate:
  certificate:
    ca.crt: #@ self.certificate["ca.crt"]
    tls.crt: #@ self.certificate["tls.crt"]
    tls.key: #@ self.certificate["tls.key"]
    certificate-hash: #@ self.certificate["certificate-hash"]
