#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ app_domains = data.values.app_domains
#@ if not app_domains:
#@   app_domains = [ data.values.domain ]
#@ end

#@overlay/match by=overlay.and_op(overlay.subset({"metadata":{"name":"istio-ingressgateway", "namespace" : "cf-system"}}), overlay.subset({"kind": "Gateway"}))
---
spec:
  servers:
  #@overlay/match by=overlay.subset({"tls": {"credentialName": "cf-system-cert"}})
  - hosts:
    #@ for domain in app_domains:
    #@overlay/append
    - #@ domain
    #@ end

