#@ if self.certificate:
#@ load("@ytt:overlay", "overlay")
---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
- path: [data]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Secret
      namespace: istio-system
      name: #@ self.istio_ingressgateway_credential_name
- path: [metadata, labels, cert.gardener.cloud/certificate-hash]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Secret
      namespace: istio-system
      name: #@ self.istio_ingressgateway_credential_name
---
apiVersion: v1
data:
  ca.crt: #@ self.certificate["ca.crt"]
  tls.crt: #@ self.certificate["tls.crt"]
  tls.key: #@ self.certificate["tls.key"]
kind: Secret
metadata:
  labels:
    cert.gardener.cloud/certificate: "true"
    cert.gardener.cloud/certificate-hash: #@ self.certificate["certificate-hash"]
  name: #@ self.istio_ingressgateway_credential_name
  namespace: istio-system
type: Opaque
---
#@overlay/match by=overlay.subset({"kind":"Secret", "metadata":{"namespace": "istio-system", "name": self.istio_ingressgateway_credential_name}})
---
metadata:
  annotations:
    #@overlay/remove
    kapp.k14s.io/versioned: ""
#@ end