#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ dnsnames = [ "*.uaa." + data.values.system_domain, "*.login." + data.values.system_domain]
#@ for sub_domain in  data.values.gardener.sub_domains:
#@   dnsnames.append(sub_domain + data.values.system_domain)
#@ end

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"namespace": "istio-system", "name":"istio-ingressgateway"}})
---
metadata:
  #@overlay/merge
  #@overlay/match missing_ok=True
  annotations:
    cert.gardener.cloud/secretname: #@ data.values.gardener.istio_ingressgateway_credential_name
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: #@ ",".join(dnsnames)
    dns.gardener.cloud/ttl: "600"

#@overlay/match by=overlay.subset({"kind":"Gateway", "metadata":{"namespace": "cf-system", "name":"istio-ingressgateway"}})
---
spec:
  servers:
    #@overlay/match by=overlay.subset({"tls": {"credentialName": "cf-system-cert"}})
    - tls:
        credentialName: #@ data.values.gardener.istio_ingressgateway_credential_name

#@overlay/match by=overlay.subset({"kind":"Secret", "metadata":{"name":"cf-system-cert"}})
#@overlay/remove
