#@ load("@ytt:base64", "base64")
#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
    name: cf-admin-password
    namespace: cf-system
type: Opaque
data:
    username: #@ base64.encode("admin")
    password: #@ base64.encode(data.values.cf_admin_password)
---
apiVersion: v1
kind: Secret
metadata:
    name: uaa-admin-client-secret
    namespace: cf-system
type: Opaque
data:
    username: #@ base64.encode("admin")
    password: #@ base64.encode(data.values.uaa.admin_client_secret)
