#@ load("@ytt:data","data")
#@ load("@ytt:base64","base64")
#@ load("@ytt:yaml", "yaml")
#@ yaml_data = yaml.encode(data.values)
#@ yaml_data = "#@data/values\n---\n" + yaml_data
#@ yaml_data = yaml_data.replace("app_domains:","#@overlay/replace\napp_domains:")
#@ yaml_data = yaml_data.replace("gardener:","#@overlay/match missing_ok=True\ngardener:")
---
apiVersion: v1
kind: Secret
metadata:
  name: cf-values
data:
  cf-values.yaml: #@ base64.encode(yaml_data)
