#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.and_op(overlay.subset({"metadata":{"name":"istio-ingress"}}), overlay.subset({"kind": "Gateway"}))
---
spec:
  servers:
  #@overlay/append
  - hosts:
    - #@ data.values.system_domain
    - #@ "*." + data.values.system_domain
    - #@ "*.authentication." + data.values.system_domain
    - #@ "*.xsuaa-api." + data.values.system_domain
    - #@ "*.dt.cpp." + data.values.system_domain
    - #@ "*.cpp." + data.values.system_domain
    - #@ "*.cockpit." + data.values.system_domain
    - #@ "operator.operationsconsole." + data.values.system_domain
    port:
      name: https-apps-example-com
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.istio_ingressgateway_credential_name }}
      mode: SIMPLE