#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.and_op(overlay.subset({"metadata":{"name":"istio-ingress"}}), overlay.subset({"kind": "Gateway"}))
---
spec:
  servers:
  #@overlay/append
  - hosts:
    - '*.{{ .Values.domain | replace "cf.ingress" "cfa.ingress" }}'
    port:
      name: https-apps-example-com
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .Values.istio_ingressgateway_credential_name }}
      mode: SIMPLE
