#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"name":"istio-ingressgateway"}})
---
  metadata:
    #@overlay/replace
    annotations:
      cert.gardener.cloud/secretname: {{ .Values.istio_ingressgateway_credential_name }}
      dns.gardener.cloud/class: garden
      dns.gardener.cloud/dnsnames: {{ .Values.domain }}
      dns.gardener.cloud/ttl: "600"

#@overlay/match by=overlay.subset({"kind":"Gateway", "metadata":{"name":"istio-ingressgateway"}})
---
spec:
  servers:
    #@overlay/match by=overlay.subset({"tls": {"credentialName": "istio-ingressgateway-certs"}})
    - tls:
        credentialName: {{ .Values.istio_ingressgateway_credential_name }}

#@overlay/match by=overlay.subset({"kind":"Secret", "metadata":{"name":"istio-ingressgateway-certs"}})
#@overlay/remove
